name: Telegram и HTML5-Validator
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Уведомление и валидация
    runs-on: ubuntu-latest
    steps:
    - name: Send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: 714086278
        token: 7127817825:AAEhwasMMff5x37gaZI5c0C9ArMnoTpi-E4
        message: |
          714086278 создал новый коммит: ${{ github.event.commits[0].message }}
          Ссылка на коммит: https://github.com/IvoryRo/-HTML-CSS-.git/commit/${{github.sha}}
          Репозиторий: https://github.com/IvoryRo/-HTML-CSS-.git
            
          CI/CD github actions: https://github.com/IvoryRo/-HTML-CSS-.git/actions
          https://github.com/IvoryRo/-HTML-CSS-.git/actions/runs/${{github.run_id}}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Пройти проверки HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action-experimental@master
      with:
        root: /
      continue-on-error: true
    